title: Tech Blog - Richard van der Els
description: Blogs over Microsoft Entra ID, Intune en Security 
author: Richard van der Els
url: "https://richardvanderels.github.io"
baseurl: ""
lang: nl
theme: minima
plugins:
  - jekyll-feed
